### PR TITLE
Issue65 Speedup GrayBat

### PR DESCRIPTION
**Pull request by erikzenker**
Introduced GrayBat recv from any adjacent vertex, such that the first vertex that sends a msg will be served first.

* Same runtime as MPI version (or even faster :-P)

### CODE REVIEW

**Comment by slizzered** [comment]
There are some unfixed warnings in the pulled GrayBat subtree, I think.

```c++
In file included from /home/eckert62/haseongpu/src/calc_phi_ase_graybat.cc:35:0:
/home/eckert62/haseongpu/include/graybat/communicationPolicy/BMPI.hpp: In constructor ‘graybat::communicationPolicy::BMPI::Event::Event(boost::mpi::request)’:
/home/eckert62/haseongpu/include/graybat/communicationPolicy/BMPI.hpp:160:16: warning: ‘graybat::communicationPolicy::BMPI::Event::request’ will be initialized after [-Wreorder]
   mpi::request request;
                ^
/home/eckert62/haseongpu/include/graybat/communicationPolicy/BMPI.hpp:159:28: warning:   ‘const bool graybat::communicationPolicy::BMPI::Event::async’ [-Wreorder]
                 const bool async;
                            ^
/home/eckert62/haseongpu/include/graybat/communicationPolicy/BMPI.hpp:108:3: warning:   when initialized here [-Wreorder]
   Event(mpi::request request) : request(request), async(true){
   ^
/home/eckert62/haseongpu/include/graybat/communicationPolicy/BMPI.hpp: In constructor ‘graybat::communicationPolicy::BMPI::Event::Event(boost::mpi::status)’:
/home/eckert62/haseongpu/include/graybat/communicationPolicy/BMPI.hpp:161:30: warning: ‘graybat::communicationPolicy::BMPI::Event::status’ will be initialized after [-Wreorder]
                 mpi::status  status;
                              ^
/home/eckert62/haseongpu/include/graybat/communicationPolicy/BMPI.hpp:159:28: warning:   ‘const bool graybat::communicationPolicy::BMPI::Event::async’ [-Wreorder]
                 const bool async;
                            ^
/home/eckert62/haseongpu/include/graybat/communicationPolicy/BMPI.hpp:112:17: warning:   when initialized here [-Wreorder]
                 Event(mpi::status status) : status(status), async(false){
                 ^
```

**Comment by erikzenker** [comment]
Okay, this was caused by unordered members in the Event class. Fixed it quick and clean.

**Comment by slizzered** [comment]
First results are here :smiley_cat

### Setup
Very similar to https://github.com/ComputationalRadiationPhysics/haseongpu/pull/58#issuecomment-114260746 . Only difference: this time, 8 nodes were used to speed up the computation a bit.

### Run with the new PR of GrayBat with 8 Nodes
 - The run finished all 150 time steps after a walltime of 0:50:32.
 - The first 140 time steps were extracted (see table below)
 - based on the 31 active GPUs, GPU time can be estimated as (0:50:32)*31 = 78492s
 - This yields an average perfomance of (78492s / 150) = 523s

### Run with the new PR of GrayBat with 2 Nodes
 - TBD


### Results
 - Elementwise comparison between the MPI run (see link) and this run yield a maximum (absolute) difference of `1.5684e-04`.
 - This is considered a valid result, so GrayBat seems to produce the correct values.
 - The longer runtime when using 8 Nodes could probably be explained by overhead produced by the MATLAB code.

| Timestep | parallel_mode = 'graybat' (8 Nodes)                | parallel_mode = 'graybat' (2 Nodes) | 
|--------|------------------------------------------------------|-------------------------------------|
|  0        | 0.79924105727549743516391345110605470836162567138672 |                       |                                  
|  1        | 0.82967902324631426225209906988311558961868286132812 |                       |
|  2        | 0.86065464598197138901269909183611162006855010986328 |                       |
|  3        | 0.89211764631769296940433378040324896574020385742188 |                       |
|  4        | 0.92401582024966666395471293071750551462173461914062 |                       |
|  5        | 0.95629181903938598185987984834355302155017852783203 |                       |
|  6        | 0.98888623154559951444753096438944339752197265625000 |                       |
|  7        | 1.02173751319121119962574084638617932796478271484375 |                       |
|  8        | 1.05478157067889788400805173296248540282249450683594 |                       |
|  9        | 1.08795325652327523613394077983684837818145751953125 |                       |
|  10       | 1.12118674243655158662136273051146417856216430664062 |                       |
|  11       | 1.15441523081499419767226299882167950272560119628906 |                       |
|  12       | 1.18757161866819327400435213348828256130218505859375 |                       |
|  13       | 1.22059289196651521436365328554529696702957153320312 |                       |
|  14       | 1.25340950145959162398412445327267050743103027343750 |                       |
|  15       | 1.28596778825772051213505164923844859004020690917969 |                       |
|  16       | 1.31819861680314831531291019928175956010818481445312 |                       |
|  17       | 1.35004952558666801998299433762440457940101623535156 |                       |
|  18       | 1.38145974878399324659028479800326749682426452636719 |                       |
|  19       | 1.41238535494249095592067533289082348346710205078125 |                       |
|  20       | 1.44277517907330432578305590141098946332931518554688 |                       |
|  21       | 1.47258200461405808212589363392908126115798950195312 |                       |
|  22       | 1.50175083870338177405301394173875451087951660156250 |                       |
|  23       | 1.53025602012058525858151369902770966291427612304688 |                       |
|  24       | 1.55805021973011426084099184663500636816024780273438 |                       |
|  25       | 1.58513674721803443645740117062814533710479736328125 |                       |
|  26       | 1.61147404996065501947555276274215430021286010742188 |                       |
|  27       | 1.63703934055330391217353280808310955762863159179688 |                       |
|  28       | 1.66180996211737985746026424749288707971572875976562 |                       |
|  29       | 1.68575068457618315598267599852988496422767639160156 |                       |
|  30       | 1.70887230650595167702476828708313405513763427734375 |                       |
|  31       | 1.73119771562435142975289181777043268084526062011719 |                       |
|  32       | 1.75269251998407171733163067983696237206459045410156 |                       |
|  33       | 1.77333864341145552856460199109278619289398193359375 |                       |
|  34       | 1.79320318088342567364179558353498578071594238281250 |                       |
|  35       | 1.81222746390682676320693644811399281024932861328125 |                       |
|  36       | 1.83048487470327070347764220059616491198539733886719 |                       |
|  37       | 1.84796500955362663631831310340203344821929931640625 |                       |
|  38       | 1.86470416174254149943578795500798150897026062011719 |                       |
|  39       | 1.88065568658344695052164752269163727760314941406250 |                       |
|  40       | 1.89588211026164188410803035367280244827270507812500 |                       |
|  41       | 1.91040803002414394384800289117265492677688598632812 |                       |
|  42       | 1.92418668207478971154955615929793566465377807617188 |                       |
|  43       | 1.93731384377214377323639382666442543268203735351562 |                       |
|  44       | 1.94979128929440648221316223498433828353881835937500 |                       |
|  45       | 1.96163568911663110938548015838023275136947631835938 |                       |
|  46       | 1.97288172909390091547265910776332020759582519531250 |                       |
|  47       | 1.98351988407477475284679258038522675633430480957031 |                       |
|  48       | 1.99357169503742515104249832802452147006988525390625 |                       |
|  49       | 2.00317622832205932681404192408081144094467163085938 |                       |
|  50       | 2.01223664315384054290802851028274744749069213867188 |                       |
|  51       | 1.95018394316558474343992202193476259708404541015625 |                       |
|  52       | 1.89318910258728934081773331854492425918579101562500 |                       |
|  53       | 1.84068780664882636344259481120388954877853393554688 |                       |
|  54       | 1.79214044783855275255746164475567638874053955078125 |                       |
|  55       | 1.74722172735053238312730172765441238880157470703125 |                       |
|  56       | 1.70550227819825117592245078412815928459167480468750 |                       |
|  57       | 1.66667764281204355825138918589800596237182617187500 |                       |
|  58       | 1.63039145550484265712043452367652207612991333007812 |                       |
|  59       | 1.59650790050154722798936290928395465016365051269531 |                       |
|  60       | 1.56470386595774035853878558555152267217636108398438 |                       |
|  61       | 1.53483314058098763155157939763739705085754394531250 |                       |
|  62       | 1.50671883030010933524067695543635636568069458007812 |                       |
|  63       | 1.48024918388678683456305407162290066480636596679688 |                       |
|  64       | 1.45526638690099963113766534661408513784408569335938 |                       |
|  65       | 1.43165249590941434654212116583948954939842224121094 |                       |
|  66       | 1.40929459755204522508620357257314026355743408203125 |                       |
|  67       | 1.38809723863382927788734377827495336532592773437500 |                       |
|  68       | 1.36798262076889542981916747521609067916870117187500 |                       |
|  69       | 1.34886700051521324361658571433508768677711486816406 |                       |
|  70       | 1.33069577550302087232125813898164778947830200195312 |                       |
|  71       | 1.31339131364773820109803637024015188217163085937500 |                       |
|  72       | 1.29689512482056379383266175864264369010925292968750 |                       |
|  73       | 1.28115715576978650425132855161791667342185974121094 |                       |
|  74       | 1.26612817449438219696844498685095459222793579101562 |                       |
|  75       | 1.25176251935713311880249420937616378068923950195312 |                       |
|  76       | 1.23802046259382936277404496649978682398796081542969 |                       |
|  77       | 1.22486460450795231480469738016836345195770263671875 |                       |
|  78       | 1.21226204040743779088984410918783396482467651367188 |                       |
|  79       | 1.20017323120257346502626205619890242815017700195312 |                       |
|  80       | 1.18857712053595299117603190097725018858909606933594 |                       |
|  81       | 1.17744427067537360542814894870389252901077270507812 |                       |
|  82       | 1.16674776621888742766941504669375717639923095703125 |                       |
|  83       | 1.15646424465430763817153092531953006982803344726562 |                       |
|  84       | 1.14657627617212765080978442711057141423225402832031 |                       |
|  85       | 1.13705824499840990604582202649908140301704406738281 |                       |
|  86       | 1.12789142416562082615882900427095592021942138671875 |                       |
|  87       | 1.11905918646281987705037863634061068296432495117188 |                       |
|  88       | 1.11054346479937171565666176320519298315048217773438 |                       |
|  89       | 1.10233033840870398023525922326371073722839355468750 |                       |
|  90       | 1.09440397649277709746229447773657739162445068359375 |                       |
|  91       | 1.08675218778618565274030061118537560105323791503906 |                       |
|  92       | 1.07936059484478974468402157071977853775024414062500 |                       |
|  93       | 1.07221906565965330315748360590077936649322509765625 |                       |
|  94       | 1.06531521070014068008902086148736998438835144042969 |                       |
|  95       | 1.05863840661769947892878462880617007613182067871094 |                       |
|  96       | 1.05217887025763423558544218394672498106956481933594 |                       |
|  97       | 1.04592663307590361121413025102810934185981750488281 |                       |
|  98       | 1.03987342943126126471042880439199507236480712890625 |                       |
|  99       | 1.03401078390834277875853786099469289183616638183594 |                       |
|  100      | 1.02833016373117813735404979524901136755943298339844 |                       |
|  101      | 1.02282448490799904305958989425562322139739990234375 |                       |
|  102      | 1.01748626130377162191109619016060605645179748535156 |                       |
|  103      | 1.01230886187067015136165082367369905114173889160156 |                       |
|  104      | 1.00728624255222354300087772571714594960212707519531 |                       |
|  105      | 1.00241226034057762106499467336107045412063598632812 |                       |
|  106      | 0.99768076790134840869939125695964321494102478027344 |                       |
|  107      | 0.99308644609382046297696433612145483493804931640625 |                       |
|  108      | 0.98862407146092601273323907662415876984596252441406 |                       |
|  109      | 0.98428880010365116248749473015777766704559326171875 |                       |
|  110      | 0.98007594612372961329072040825849398970603942871094 |                       |
|  111      | 0.97598101546387816540573112433776259422302246093750 |                       |
|  112      | 0.97199970816129066530919544675271026790142059326172 |                       |
|  113      | 0.96812768863179654577066912679583765566349029541016 |                       |
|  114      | 0.96436155250989630260960439045447856187820434570312 |                       |
|  115      | 0.96069707314523844488007853215094655752182006835938 |                       |
|  116      | 0.95713120518139127579360092568094842135906219482422 |                       |
|  117      | 0.95366004773104462444166529166977852582931518554688 |                       |
|  118      | 0.95028083968622367727618893695762380957603454589844 |                       |
|  119      | 0.94699047393009827544574363855645060539245605468750 |                       |
|  120      | 0.94378581739776779002681905694771558046340942382812 |                       |
|  121      | 0.94066383588623980749332531559048220515251159667969 |                       |
|  122      | 0.93762211473113321602568248636089265346527099609375 |                       |
|  123      | 0.93465800681812805095205476391129195690155029296875 |                       |
|  124      | 0.93176916906692008879531385900918394327163696289062 |                       |
|  125      | 0.92895293620670205125833263082313351333141326904297 |                       |
|  126      | 0.92620687029267712020441649656277149915695190429688 |                       |
|  127      | 0.92352908853477955197774917905917391180992126464844 |                       |
|  128      | 0.92091729206519046257994887128006666898727416992188 |                       |
|  129      | 0.91836969854787242617533138400176540017127990722656 |                       |
|  130      | 0.91588414485016977906184365565422922372817993164062 |                       |
|  131      | 0.91345834531663261390832531105843372642993927001953 |                       |
|  132      | 0.91109119856288134364774577989010140299797058105469 |                       |
|  133      | 0.90878033675643354882822677609510719776153564453125 |                       |
|  134      | 0.90652518886124355823596943082520738244056701660156 |                       |
|  135      | 0.90432336887987396778498805360868573188781738281250 |                       |
|  136      | 0.90217308161716625036774530599359422922134399414062 |                       |
|  137      | 0.90007335451173298146443357836687937378883361816406 |                       |
|  138      | 0.89802289739336449425621822229004465043544769287109 |                       |
|  139      | 0.89601973267369250386593648727284744381904602050781 |                       |

**Comment by slizzered** [comment]
Looks even a bit faster than the MPI code! Cool stuff!

**Pull request merged**
